# Generated by Django 2.2 on 2026-01-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20260115_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('imei', models.CharField(max_length=15)),
                ('percent', models.IntegerField()),
                ('is_charging', models.BooleanField()),
                ('busy_time', models.IntegerField()),
            ],
        ),
    ]
