# Generated by Django 2.2 on 2026-01-18 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_terminalmonitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalmonitor',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
