# Generated by Django 2.2 on 2026-01-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20260118_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalmonitor',
            name='up_time',
            field=models.IntegerField(default=2012910),
        ),
    ]
