# Generated by Django 2.2 on 2026-01-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_terminalmonitor_up_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TerminalMonitor',
        ),
    ]
