# Generated by Django 2.2 on 2026-03-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_delete_terminalmonitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d/'),
        ),
    ]
